export { default as About } from "./About";
export { default as CardsContainer } from "./CardsContainer";
export { default as Contacts } from "./Contacts";
export { default as PastaWork } from "./PastaWork";
export { default as WineWork } from "./WineWork";
export { default as Navbar } from "./Navbar/Navbar";
export { default as Cart } from "./Cart/Cart";
export { default as Checkout } from "./CheckoutForm/Checkout/Checkout";
export { default as Main } from "./Main/Main";
