export { default as About } from "./About/About";
export { default as Cards } from "./Cards/Cards";
export { default as Contacts } from "./Contacts/Contacts";
export { default as PastaWork } from "./PastaWork/PastaWork";
export { default as WineWork } from "./WineWork/WineWork";
export { default as Navbar } from "./Navbar/Navbar";
export { default as Cart } from "./Cart/Cart";
export { default as Checkout } from "./CheckoutForm/Checkout/Checkout";
export { default as Main } from "./Main/Main";
